darmstadt_termine/urls.py
from django.urls import include, path

from . import views

app_name = "darmstadt_termine"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_notification, name="register"),
    path(
        "activate/<idb64>/<token>/",
        views.activate_notification,
        name="activate",
    ),
    path("edit/<token>/", views.edit_notification, name="edit"),
    path("delete/<token>/", views.delete_notification, name="delete"),
    path(
        "delete/<idb64>/<token>/",
        views.delete_notification,
        name="delete",
    ),
    path(
        "reset/",
        include(
            [
                path("", views.reset_notification, name="reset"),
                path(
                    "confirm/<idb64>/<token>/",
                    views.reset_notification_confirm,
                    name="reset_confirm",
                ),
            ]
        ),
    ),
]

darmstadt_termine/templates/darmstadt_termine/include/current_appointments.html
{% load i18n %}
<h2>{% translate "Aktuell verfügbare Termine:" %}</h2>
<p>
    <div class="ms-3">
        {% regroup appointment_types_list by appointment_category as appointment_categories %}
        {% for appointment_category in appointment_categories %}
            <p>{{ appointment_category.grouper }}:</p>
            <div class="ms-3">
                <div class="accordion" id="current_appointments">
                    {% for appointment_type in appointment_category.list %}
                        {% if appointment_type.appointments %}
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button type="button"
                                            class="accordion-button collapsed"
                                            data-bs-toggle="collapse"
                                            data-bs-target="#type_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}"
                                            aria-expanded="false"
                                            aria-controls="type_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}">
                                        {{ appointment_type.name }}
                                    </button>
                                </h2>
                                <div id="type_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}"
                                     class="accordion-collapse collapse"
                                     data-bs-parent="#current_appointments">
                                    <div class="accordion-body">
                                        {% regroup appointment_type.appointments by date as date_list %}
                                        <table class="table table-striped table-hover">
                                            <thead>
                                                <tr>
                                                    <th scope="col">{% translate "Datum" %}</th>
                                                    <th scope="col">{% translate "Verfügbare Zeiten" %}</th>
                                                    <th scope="col">{% translate "Ort" %}</th>
                                                </tr>
                                            </thead>
                                            <tbody class="table-group-divider">
                                                {% for appointments in date_list %}
                                                    {# djlint:off H025 #}
                                                    <tr>
                                                        {# djlint:on H025 #}
                                                        <th scope="row" rowspan="{{ appointments.list|length }}">
                                                            <div class="sticky-top">{{ appointments.grouper }}</div>
                                                        </th>
                                                        {% for appointment in appointments.list %}
                                                            {% if not forloop.first %}<tr>{% endif %}
                                                                <td>{{ appointment.start_time }}-{{ appointment.end_time }}</td>
                                                                <td>{{ appointment.location__name }}</td>
                                                            </tr>
                                                        {% endfor %}
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <p>{% translate "Keine Termine verfügbar." %}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% empty %}
                <p>{% translate "Keine Termine verfügbar." %}</p>
            {% endfor %}
        </div>
    </p>

darmstadt_termine/templates/darmstadt_termine/include/delete_url.html
{% load i18n %}
{% load notification_tags %}
<p>{% translate "Mit folgendem Link können Sie sich von weiteren Benachrichtigungen abmelden:" %}</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url "darmstadt_termine:delete" idb64=idb64 token=token %}"
       target="_blank"
       rel="noopener noreferrer">{{ protocol }}://{{ domain }}{% url "darmstadt_termine:delete" idb64=idb64 token=token %}</a>
</p>
<p>{% blocktranslate with time=timeout|timedelta %}Dieser Link ist aktiv für {{time}}.{% endblocktranslate %}</p>

darmstadt_termine/templates/darmstadt_termine/include/edit_url.html
{% load i18n %}
<p>
    {% blocktranslate %}Unter folgendem Link können Sie einstellen für welche Termine Sie Benachrichtigungen erhalten:{% endblocktranslate %}
</p>
<p>
    <a class="text-break"
       href="{% url "darmstadt_termine:edit" token=token %}"
       target="_blank"
       rel="noopener noreferrer">{{ protocol }}://{{ domain }}{% url "darmstadt_termine:edit" token=token %}</a>
</p>
<p>
    {% translate "Alternativ können Sie folgenden Token nutzen:" %}
    <div class="user-select-all text-break">{{ token }}</div>
</p>
<p>
    <strong>{% translate "ACHTUNG: Bitte den Link oder Token kopieren und speichern! Dieser Link/Token ist nur jetzt verfügbar!" %}</strong>
</p>