darmstadt_termine/urls.py
from django.urls import include, path

from . import views

app_name = "darmstadt_termine"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_notification, name="register"),
    path(
        "activate/<idb64>/<token>/",
        views.activate_notification,
        name="activate",
    ),
    path("edit/<token>/", views.edit_notification, name="edit"),
    path("delete/<token>/", views.delete_notification, name="delete"),
    path(
        "delete/<idb64>/<token>/",
        views.delete_notification,
        name="delete",
    ),
    path(
        "reset/",
        include(
            [
                path("", views.reset_notification, name="reset"),
                path(
                    "confirm/<idb64>/<token>/",
                    views.reset_notification_confirm,
                    name="reset_confirm",
                ),
            ]
        ),
    ),
]

darmstadt_termine/templates/darmstadt_termine/activate.html
{% extends "darmstadt_termine/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
    <p>{% translate "Ihre Benachrichtigung wurde erfolgreich aktiviert!" %}</p>
    {% include "darmstadt_termine/include/edit_url.html" with token=token protocol=protocol domain=domain %}
{% endblock content %}

darmstadt_termine/templates/darmstadt_termine/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
    </head>
    <body>
        <div class="container mt-4">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                         role="alert">
                        {{ message }}
                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="alert"
                                aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
        {% block javascript %}
        {% endblock javascript %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
    </body>
</html>

darmstadt_termine/templates/darmstadt_termine/edit.html
{% extends "darmstadt_termine/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="row">
            <div class="col">
                <button class="btn btn-success" type="submit">{% translate "Speichern" %}</button>
            </div>
            <div class="col-auto">
                <a class="btn btn-danger"
                   href="{% url "darmstadt_termine:delete" token=token %}">{% translate "Löschen" %}</a>
            </div>
        </div>
    </form>
{% endblock content %}
{% block javascript %}
    {{ form.media.js }}
{% endblock javascript %}

darmstadt_termine/templates/darmstadt_termine/index.html
{% extends "darmstadt_termine/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    {% translate "Termintracker für Termine der Stadt Darmstadt" %}
{% endblock title %}
{% block content %}
    <h1>{% translate "Termintracker für Termine der Stadt Darmstadt" %}</h1>
    <hr>
    <div class="row">
        <div class="col-md mb-md-0 mb-3">
            <h2>{% translate "Registrieren um Benachrichtigungen zu neuen Terminen zu erhalten:" %}</h2>
            <a href="{% url "darmstadt_termine:register" %}" class="btn btn-primary">{% translate "Jetzt Registrieren" %}</a>
        </div>
        <div class="col-md">
            <h2>{% translate "Bereits registrierte Benachrichtigungen bearbeiten:" %}</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {{ edit_login_form|crispy }}
                <button class="btn btn-primary" type="submit">{% translate "Zu den Einstellungen" %}</button>
            </form>
            <small class="text-secondary">
                {% translate "Token vergessen?" %} <a href="{% url "darmstadt_termine:reset" %}" class="link-secondary">{% translate "Neuen Token anfordern" %}</a>
            </small>
        </div>
    </div>
    <hr>
    {% include "darmstadt_termine/include/current_appointments.html" with appointment_types_list=appointment_types_list %}
    <p>{% translate "Hier kommen bald Statistiken über verfügbare Termine hin." %}</p>
    {% comment %} <div>
        <canvas id="first_time_appointments_chart"></canvas>
    </div> {% endcomment %}
{% endblock content %}
{% block javascript %}
    {% comment %} {{ first_time_appointments|json_script:"first_time_appointments" }}
    <script src="{% static "darmstadt_termine/js/chart.umd.min.js" %}"></script>
    <script src="{% static "darmstadt_termine/js/stats.js" %}"></script> {% endcomment %}
{% endblock javascript %}

darmstadt_termine/templates/darmstadt_termine/register.html
{% extends "darmstadt_termine/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <button class="btn btn-success" type="submit">{% translate "Registrieren" %}</button>
        </div>
    </form>
{% endblock content %}
{% block javascript %}
    {{ form.media.js }}
{% endblock javascript %}

darmstadt_termine/templates/darmstadt_termine/reset.html
{% extends "darmstadt_termine/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <button class="btn btn-success" type="submit">{% translate "Zurücksetzen" %}</button>
        </div>
    </form>
{% endblock content %}

darmstadt_termine/templates/darmstadt_termine/reset_complete.html
{% extends "darmstadt_termine/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
    <p>{% translate "Ihre Benachrichtigung wurde erfolgreich zurückgesetzt!" %}</p>
    {% include "darmstadt_termine/include/edit_url.html" with token=token protocol=protocol domain=domain %}
{% endblock content %}